databases:
  - name: todo-db
    databaseName: todoapp
    user: todouser
    plan: free

services:
  - type: web
    name: todo-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_CONNECTION_TIMEOUT
        value: "30000"
      - key: DB_MINIMUM_IDLE
        value: "2"
      - key: DB_MAXIMUM_POOL_SIZE
        value: "5"
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"