databases:
  - name: todo-db
    databaseName: todoapp
    user: todouser
    plan: free

services:
  - type: web
    name: todo-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_TYPE
        value: postgresql
      - key: DB_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: DB_URL
        fromDatabase:
          name: todo-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: todo-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: todo-db
          property: password
      - key: DB_CONNECTION_TIMEOUT
        value: "30000"
      - key: DB_MINIMUM_IDLE
        value: "2"
      - key: DB_MAXIMUM_POOL_SIZE
        value: "5"
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"